# Nashville Housing Data

In [7]:
import sqlite3
import csv

import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

## Part 1. Reading CSV file
We can use *pd.read_csv()* function to read a csv file and convert into panda dataframe. 
In the example below, we are assuming that the "nashville_housing.csv" is stored in the 
current folder (i.e. in the same folder where this notebook is stored)

```python
df = pd.read_csv("nashville_housing.csv")
```

### Q1a. [10pts] Read the input file using the *pd.read_csv()* function and store inside a panda dataframe

In [12]:
# YOUR CODE HERE
df = pd.read_csv("nashville_housing.csv")
del df['Unnamed: 0']
del df['Unnamed: 0.1']
df.head()

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,...,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,1/24/13,132000,20130128-0008725,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,1/11/13,191500,20130118-0006337,No,No,...,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,1/18/13,202000,20130124-0008033,No,No,...,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,1/18/13,32000,20130128-0008863,No,No,...,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,1/23/13,102000,20130131-0009929,No,No,...,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0

## Part 2. Data selection
In this part, your task is to write codes to filter the dataset by selecting rows whose column match some conditions.

### Q2a. [10pts] Select and show all the houses that were sold for more than 1 000 000 USD.

In [11]:
# YOUR CODE HERE
df[df['Sale Price'] > 1000000]

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Price,Owner Name,City,State,Acreage,Tax District,Neighborhood,Land Value,Building Value,Total Value,Finished Area,Year Built,Bedrooms,Full Bath,Half Bath
140,117 10 0 015.00,SINGLE FAMILY,2205 WOODMONT BLVD,NaN,NASHVILLE,1435000,"O'HAGAN, PAUL A. P. & NEAL, JUDITH A.",NASHVILLE,TN,1.58,URBAN SERVICES DISTRICT,3227.0,398000.0,971700.0,1402300.0,6753.00000,1942.0,5.0,4.0,2.0
193,144 06 0 010.00,SINGLE FAMILY,4400 CHICKERING LN,NaN,NASHVILLE,2760000,"CLN30 TRUST, THE",NASHVILLE,TN,4.53,CITY OF BELLE MEADE,9026.0,1174500.0,1574300.0,2826100.0,8403.86999,1930.0,4.0,6.0,0.0
194,144 06 0 039.00,VACANT RES LAND,0 MILLER CIR,NaN,NASHVILLE,2760000,"CLN30 TRUST, THE",NASHVILLE,TN,3.59,CITY OF BELLE MEADE,9026.0,782500.0,0.0,782500.0,NaN,NaN,NaN,0.0,0.0
202,158 03 0 003.00,SINGLE FAMILY,2001 CROMWELL DR,NaN,NASHVILLE,1525000,CASTO LIVING TRUST,NASHVILLE,TN,1.04,CITY OF FOREST HILLS,9226.0,315000.0,1164100.0,1503800.0,6844.00000,1956.0,4.0,4.0,0.0
203,158 11 0A 006.00,SINGLE FAMILY,340 WHITE SWANS XING,NaN,BRENTWOOD,2562600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,159 00 0 261.00,SINGLE FAMILY,5442 GRANNY WHITE PIKE,NaN,BRENTWOOD,1365000,"HAMMAN, JACO INTER VIVOS REVOCABLE TRUST",BRENTWOOD,TN,1.99,GENERAL SERVICES DISTRICT,6528.0,280800.0,1184700.0,1465500.0,6079.00000,2006.0,4.0,4.0,1.0
205,159 07 0A 011.00,SINGLE FAMILY,5032 HIGH VALLEY DR,NaN,BRENTWOOD,1550000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,160 02 0 012.00,SINGLE FAMILY,824 REDWOOD DR,NaN,NASHVILLE,1200000,"INGRASSIA, JOHN A.",NASHVILLE,TN,1.08,CITY OF OAK HILL,9529.0,200000.0,1408800.0,1660700.0,6342.00000,2007.0,3.0,3.0,2.0
527,104 02 1G 003.00,RESIDENTIAL CONDO,3123 PARTHENON AVE,NaN,NASHVILLE,1249000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,104 09 0 238.00,SINGLE FAMILY,205 BOWLING AVE,NaN,NASHVILLE,1125000,"MILLER, GEORGE M., II & DANA R.",NASHVILLE,TN,0.41,URBAN SERVICES DISTRICT,2626.0,210000.0,915000.0,1125000.0,4101.57004,1908.0,4.0,3.0,0.0
536,104 14 0H 080.00,SINGLE FAMILY,34 OLD CLUB CT,NaN,NASHVILLE,1380000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,116 10 0 074.00,SINGLE FAMILY,224 DEER PARK CIR,NaN,NASHVILLE,1025000,"ROWLAND, JOHN H. & LINA A.",NASHVILLE,TN,0.43,CITY OF BELLE MEADE,9026.0,482600.0,519800.0,1002400.0,3555.00000,1928.0,4.0,3.0,1.0
573,117 09 0 057.00,SINGLE FAMILY,2430 BEAR RD,NaN,NASHVILLE,1700000,"BENNETT, MARTIN & LINDA",NASHVILLE,TN,1.33,URBAN SERVICES DISTRICT,3227.0,240000.0,1826100.0,2115400.0,15378.00000,1948.0,10.0,10.0,0.0
576,117 13 0B 140.00,SINGLE FAMILY,910 BOWRING PARK,NaN,NASHVILLE,1158000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,130 16 0 013.00,SINGLE FAMILY,4500 ALCOTT DR,NaN,NASHVILLE,1355000,"MASON, STEVEN J., JR. & LAURA C.",NASHVILLE,TN,1.01,CITY OF FOREST HILLS,9226.0,349600.0,976700.0,1326300.0,5727.00000,2012.0,5.0,5.0,2.0
629,146 05 0 002.00,SINGLE FAMILY,963 OVERTON LEA RD,NaN,NASHVILLE,1100000,"CHEN, ROBERT L. & ZAK, BEVERLY M.",NASHVILLE,TN,9.28,CITY OF OAK HILL,9529.0,625600.0,528900.0,1254200.0,8396.00000,1951.0,6.0,5.0,0.0
630,146 10 0 076.00,SINGLE FAMILY,828 OTTER CREEK RD,NaN,NASHVILLE,1550000,"CARTWRIGHT, MELZENA, TRUSTEE",NASHVILLE,TN,2.12,CITY OF OAK HILL,9529.0,357600.0,1386600.0,1744200.0,8959.01502,2009.0,5.0,4.0,1.0
1016,104 09 0 117.00,SINGLE FAMILY,3713 RICHLAND AVE,NaN,NASHVILLE,1500000,"WILLIS-BROOKS INVESTMENTS, L.P.",NASHVILLE,TN,0.23,URBAN SERVICES DISTRICT,2626.0,195000.0,749400.0,944400.0,5219.20005,1920.0,5.0,5.0,0.0
1057,116 10 0 065.00,SINGLE FAMILY,221 DEER PARK CIR,NaN,NASHVILLE,1350000,"RZASNICKI, STEPHEN WALTER & ANGELA",NASHVILLE,TN,0.43,CITY OF BELLE MEADE,9026.0,482600.0,742400.0,1225000.0,4345.00000,1923.0,5.0,4.0,1.0
1095,130 02 0 140.01,SINGLE FAMILY,515 JACKSON BLVD,NaN,NASHVILLE,2500000,"BROWN, EDWARD BRIAN & VIVIAN",NASHVILLE,TN,3.26,CITY OF BELLE MEADE,9026.0,1170000.0,0.0,1170000.0,NaN,NaN,NaN,NaN,NaN
1099,130 03 0 122.00,SINGLE FAMILY,540 JACKSON BLVD,NaN,NASHVILLE,7200000,"CHAPMAN, WILLIAM T. IV, TRUSTEE",NASHVILLE,TN,7.88,CITY OF BELLE MEADE,9026.0,1830700.0,3768000.0,5697100.0,10519.29993,1990.0,5.0,8.0,0.0
1152,144 13 0 013.00,VACANT RES LAND,4321 CHICKERING LN,NaN,NASHVILLE,1800000,"ANDREWS, WILLIAM J. CHRISTOPHER, TRUSTEE",NASHVILLE,TN,4.27,CITY OF FOREST HILLS,9226.0,777100.0,3563100.0,4455200.0,11034.00000,2015.0,7.0,7.0,1.0
1805,116 14 0 130.00,SINGLE FAMILY,407 JACKSON BLVD,NaN,NASHVILLE,1875000,"BLESS HER HEART, LLC",NASHVILLE,TN,0.92,CITY OF BELLE MEADE,9026.0,722300.0,1350900.0,2073200.0,6136.00000,1994.0,4.0,4.0,0.0
1815,117 04 0 257.00,SINGLE FAMILY,2812 OAKLAND AVE,NaN,NASHVILLE,1050000,"MCSHANE, TRAVIS JOSEPH",NASHVILLE,TN,0.19,URBAN SERVICES DISTRICT,2226.0,180000.0,802100.0,994000.0,4760.52002,1918.0,4.0,4.0,1.0
1875,130 02 0 156.00,SINGLE FAMILY,4418 IROQUOIS AVE,NaN,NASHVILLE,2175000,PARRISH HOUSE TRUST,NASHVILLE,TN,1.56,CITY OF BELLE MEADE,9026.0,953400.0,1012900.0,1970500.0,5572.00000,1915.0,4.0,4.0,1.0
1967,144 00 0 036.00,SINGLE FAMILY,5748 HILLSBORO PIKE,NaN,NASHVILLE,1600000,"ALLEN, WILLIAM C. & JUDSON C.",NASHVILLE,TN,3.02,CITY OF FOREST HILLS,9226.0,522600.0,645800.0,1266500.0,3656.00000,2002.0,2.0,2.0,1.0
1968,144 00 0 058.00,SINGLE FAMILY,5910 HILLSBORO PIKE,NaN,NASHVILLE,1500000,"TOMPKINS, CHRIS & JESSICA",NASHVILLE,TN,5.56,CITY OF FOREST HILLS,9226.0,599800.0,2060100.0,2724800.0,8519.39990,1990.0,6.0,5.0,1.0
1989,158 03 0 018.00,SINGLE FAMILY,6121 GARDENDALE DR,NaN,NASHVILLE,1450000,"ROBERSON, JOHN E. & KATHRYN D.",NASHVILLE,TN,1.15,CITY OF FOREST HILLS,9226.0,315000.0,1094200.0,1409200.0,6506.00000,2007.0,5.0,5.0,2.0
2290,064 03 0C 032.00,SINGLE FAMILY,1112 SAFETY HARBOR CV,NaN,OLD HICKORY,1295000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2872,104 13 0 273.00,SINGLE FAMILY,701 MILLSTONE LN,NaN,NASHVILLE,1250000,"LEHMANN, CHRISTOPH U. & PUCKETT, ANNE LYNNE",NASHVILLE,TN,0.48,URBAN SERVICES DISTRICT,3227.0,324000.0,893400.0,1246800.0,5310.00000,2002.0,5.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55589,102 11 0A 033.00,RESIDENTIAL CONDO,6813 CHARLOTTE PIKE,2,NASHVILLE,4614550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55590,102 11 0A 034.00,RESIDENTIAL CONDO,6813 CHARLOTTE PIKE,1,NASHVILLE,4614550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55593,102 16 0 060.00,SINGLE FAMILY,508 HUCKLEBERRY RD,NaN,NASHVILLE,1919500,"SCRUGGS, JESSE EARL & GARWOOD, SUSAN KAY",NASHVILLE,TN,1.25,URBAN SERVICES DISTRICT,4427.0,190000.0,1207800.0,1449700.0,6980.00000,2009.0,5.0,4.0,2.0
55613,103 16 0 093.00,SINGLE FAMILY,3901 KIMPALONG AVE,NaN,NASHVILLE,1549000,"HAYS, CHERYL",NASHVILLE,TN,0.41,URBAN SERVICES DISTRICT,3227.0,198800.0,728600.0,927400.0,4453.00000,2016.0,4.0,4.0,1.0
55647,104 15 0 497.00,SINGLE FAMILY,2530 BASHWOOD AVE,NaN,NASHVILLE,1025000,"DALE, CORINNE HOWELL & REDDING, JOSEPH MICHAEL",NASHVILLE,TN,0.18,URBAN SERVICES DISTRICT,2426.0,214500.0,389700.0,636200.0,3102.00000,2014.0,4.0,3.0,1.0
55648,104 16 0 255.00,SINGLE FAMILY,1807 BEECHWOOD AVE,NaN,NASHVILLE,1325000,"SIEGEL, JANE & DYER, CALVIN R.",NASHVILLE,TN,0.24,URBAN SERVICES DISTRICT,2226.0,180000.0,792600.0,972600.0,5985.87000,1925.0,5.0,6.0,0.0
55668,105 13 0 321.00,SINGLE FAMILY,916 BRADFORD AVE,NaN,NASHVILLE,1021974,"HESTER, DOUGLAS L. & SYDNEY M.",NASHVILLE,TN,0.18,URBAN SERVICES DISTRICT,1626.0,140000.0,442700.0,608600.0,3103.00000,2016.0,3.0,4.0,0.0
55688,115 16 0 054.00,SINGLE FAMILY,6131 JOCELYN HOLLOW RD,NaN,NASHVILLE,1433200,"HESSEL, BRENT D. & BARBARA V. & FRANK JAY",NASHVILLE,TN,1.24,URBAN SERVICES DISTRICT,4429.0,250000.0,1094500.0,1344500.0,6059.00000,2016.0,4.0,4.0,2.0
55689,116 02 0B 016.00,SINGLE FAMILY,2029 FRANSWORTH DR,NaN,NASHVILLE,1759000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55700,116 11 0 069.00,SINGLE FAMILY,315 WALNUT DR,NaN,NASHVILLE,1400000,"CCK PROJECTS, LLC",NASHVILLE,TN,0.75,CITY OF BELLE MEADE,9026.0,650000.0,843400.0,1493400.0,4684.00000,1950.0,5.0,6.0,0.0
55701,116 12 0L 003.00,SINGLE FAMILY,4209 ARUNDEL CT,NaN,NASHVILLE,1300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55703,116 14 0 015.00,SINGLE FAMILY,112 BELLEVUE DR S,NaN,NASHVILLE,1850000,"SOLOMON, PATRICK & BARBARA",NASHVILLE,TN,0.80,CITY OF BELLE MEADE,9026.0,546800.0,326900.0,873700.0,5240.00000,2016.0,5.0,6.0,2.0
55704,116 14 0 119.00,SINGLE FAMILY,514 PARK CENTER DR,NaN,NASHVILLE,2500000,"FOX, CHARLES BRIAN & MEGAN M.",NASHVILLE,TN,1.00,CITY OF BELLE MEADE,9026.0,722300.0,1914400.0,2706700.0,8634.09997,1988.0,6.0,6.0,0.0
55706,117 01 0 138.00,SINGLE FAMILY,804 TIMBER LN,NaN,NASHVILLE,1287800,"WEITKAMP, JOERN-HENDRIK & ASLI",NASHVILLE,TN,0.75,URBAN SERVICES DISTRICT,3226.0,350000.0,472700.0,822700.0,4473.12000,1939.0,5.0,4.0,0.0
55716,117 05 0 183.00,SINGLE FAMILY,3629 WOODMONT BLVD,NaN,NASHVILLE,1322500,"ZAGER, LISA",NASHVILLE,TN,0.19,URBAN SERVICES DISTRICT,3227.0,240000.0,728200.0,968200.0,4566.00000,2016.0,4.0,4.0,0.0
55717,117 06 0 058.00,SINGLE FAMILY,3422 HAMPTON AVE,NaN,NASHVILLE,1550000,"RIEBELING, BROOKE BLOOM",NASHVILLE,TN,0.91,URBAN SERVICES DISTRICT,3227.0,240000.0,666400.0,944600.0,4631.00000,1940.0,5.0,3.0,0.0
55729,118 01 0 026.00,SINGLE FAMILY,1320 SWEETBRIAR AVE,NaN,NASHVILLE,1200000,"PANTOJA, ROBERTO G.",NASHVILLE,TN,0.22,URBAN SERVICES DISTRICT,2228.0,180000.0,513900.0,737800.0,3426.00000,2012.0,4.0,3.0,1.0
55730,118 01 0 149.00,SINGLE FAMILY,1113 HALCYON AVE,NaN,NASHVILLE,1027545,"BODNAR, JAMES MATTHEW & SAMANTHA",NASHVILLE,TN,0.17,URBAN SERVICES DISTRICT,1626.0,140000.0,438000.0,578000.0,3122.00000,2016.0,4.0,4.0,0.0
55748,118 14 0C 002.00,RESIDENTIAL CONDO,3602 BCALDWELL CT,NaN,NASHVILLE,1124900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55767,130 05 0 085.00,SINGLE FAMILY,119 TAGGART AVE,NaN,NASHVILLE,1772998,"ORLANDO, TONY MICHAEL & GORDON, MARY JENNIFER",NASHVILLE,TN,0.46,URBAN SERVICES DISTRICT,4327.0,295000.0,663400.0,967500.0,5047.00000,2016.0,4.0,3.0,2.0
55789,131 06 0P 001.00,RESIDENTIAL CONDO,2012 CASTLEMAN DR,NaN,NASHVILLE,1199000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55794,131 08 0M 014.00,SINGLE FAMILY,1308 DUNCANWOOD CT,NaN,NASHVILLE,1235000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55797,131 16 0 050.00,SINGLE FAMILY,1024 GRASSLAND LN,NaN,NASHVILLE,2077500,"JARRELL, GLEN R. & KELTON R.",NASHVILLE,TN,1.30,CITY OF OAK HILL,9529.0,268900.0,1346100.0,1615000.0,6467.00000,2016.0,5.0,5.0,1.0
55800,132 06 0 005.00,SINGLE FAMILY,4032 OVERBROOK CT,NaN,NASHVILLE,2030000,"RIGGS, JEFFREY A.",NASHVILLE,TN,1.80,CITY OF OAK HILL,9528.0,311800.0,1321700.0,1633500.0,6889.00000,2016.0,5.0,5.0,1.0
55856,144 03 0 031.00,SINGLE FAMILY,1092 LYNNWOOD BLVD,NaN,NASHVILLE,1917000,"WALLACE, ROBERT B. & LAWSON, DEBORAH J.",NASHVILLE,TN,1.15,CITY OF FOREST HILLS,9226.0,425000.0,1588700.0,2013700.0,7853.70011,2007.0,4.0,5.0,2.0
55857,145 00 0 002.00,SINGLE FAMILY,5742 LAURA HILL RD,NaN,NASHVILLE,1062500,"CAPUTO, CHRISTOPHER & JULIE RYAN",NASHVILLE,TN,4.04,CITY OF FOREST HILLS,9226.0,543200.0,348300.0,891500.0,4716.00000,1959.0,3.0,4.0,0.0
55861,145 06 0 004.00,SINGLE FAMILY,5815 STILL HOLLOW RD,NaN,NASHVILLE,1095000,"ECKHARD, FELIX M. & LAPPE, KATHLEEN A.",NASHVILLE,TN,1.86,CITY OF FOREST HILLS,9226.0,315000.0,469000.0,784000.0,4024.00000,1963.0,4.0,4.0,1.0
56311,054 09 0A 002.00,SINGLE FAMILY,717 LAKE SHORE PT,NaN,OLD HICKORY,1325000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56331,064 03 0C 028.00,SINGLE FAMILY,1101 SAFETY HARBOR CV,NaN,OLD HICKORY,1380000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56620,082 09 0J 507.00,RESIDENTIAL CONDO,428 VAN BUREN ST,NaN,NASHVILLE,1050000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q2b. [10pts] Select and show all the houses that are located in Brentwood

In [7]:
# YOUR CODE HERE
df[df['Property City'].str.upper() == 'BRENTWOOD']

,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,...,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
25,160 11 0A 088.00,SINGLE FAMILY,5510 HEARTHSTONE LN,NaN,BRENTWOOD,1/15/13,270000,20130117-0005616,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,160 16 0B 019.00,SINGLE FAMILY,6144 BRENTWOOD CHASE DR,NaN,BRENTWOOD,1/25/13,295000,20130128-0008669,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,171 03 0B 082.00,RESIDENTIAL CONDO,641 OLD HICKORY BLVD,144,BRENTWOOD,1/25/13,261000,20130131-0010140,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,171 03 0B 193.00,RESIDENTIAL CONDO,641 OLD HICKORY BLVD,403,BRENTWOOD,1/17/13,234900,20130124-0007900,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,171 03 0B 212.00,RESIDENTIAL CONDO,601 OLD HICKORY BLVD,18,BRENTWOOD,1/18/13,180000,20130122-0006940,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,171 04 0C 051.00,RESIDENTIAL CONDO,835 BARRINGTON PLACE DR,NaN,BRENTWOOD,1/10/13,254800,20130116-0005140,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,171 08 0C 011.00,VACANT RES LAND,5834 PETERSBURG LN,NaN,BRENTWOOD,1/7/13,80000,20130108-0002385,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,181 03 0A 290.00,VACANT RES LAND,7520 STECOAH ST,NaN,BRENTWOOD,1/22/13,45000,20130125-0008288,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,181 10 0D 012.00,VACANT RES LAND,449 HIGH POINT TER,NaN,BRENTWOOD,1/28/13,80000,20130130-0009574,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,181 11 0B 113.00,SINGLE FAMILY,9132 CARISSA DR,NaN,BRENTWOOD,1/7/13,200000,20130110-0003093,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,158 11 0A 006.00,SINGLE FAMILY,340 WHITE SWANS XING,NaN,BRENTWOOD,1/11/13,2562600,20130115-0004883,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,159 00 0 261.00,SINGLE FAMILY,5442 GRANNY WHITE PIKE,NaN,BRENTWOOD,1/2/13,1365000,20130104-0001158,No,No,...,1184700.0,1465500.0,6079.00000,CRAWL,2006.0,BRICK,X,4.0,4.0,1.0
205,159 07 0A 011.00,SINGLE FAMILY,5032 HIGH VALLEY DR,NaN,BRENTWOOD,1/31/13,1550000,20130201-0010419,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,160 10 0A 008.00,SINGLE FAMILY,101 HEATHER WAY,NaN,BRENTWOOD,2/22/13,345000,20130228-0020255,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,160 11 0 046.00,SINGLE FAMILY,5608 HEARTHSTONE LN,NaN,BRENTWOOD,2/7/13,300000,20130219-0016493,No,No,...,293600.0,353600.0,3420.00000,CRAWL,1987.0,BRICK,B,3.0,3.0,0.0
452,160 11 0A 115.00,SINGLE FAMILY,39 ASHINGTON LN,NaN,BRENTWOOD,2/15/13,351000,20130214-0015284,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,160 14 0B 128.00,RESIDENTIAL CONDO,5832 BRENTWOOD TRCE,NaN,BRENTWOOD,2/4/13,123000,20130208-0013446,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,160 14 0C 011.00,RESIDENTIAL CONDO,711 FOX RIDGE DR,NaN,BRENTWOOD,2/11/13,128000,20130212-0014422,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,171 04 0A 058.00,SINGLE FAMILY,5557 NEVIL PT,NaN,BRENTWOOD,2/22/13,322900,20130227-0019689,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,171 07 0B 005.00,VACANT RES LAND,226 JONES PKWY,NaN,BRENTWOOD,2/14/13,170000,20130220-0016606,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,181 03 0A 291.00,VACANT RES LAND,7977 OAKFIELD GRV,NaN,BRENTWOOD,2/20/13,45000,20130221-0017482,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,181 10 0D 019.00,SINGLE FAMILY,477 HIGH POINT TER,NaN,BRENTWOOD,2/15/13,372258,20130222-0017775,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,181 10 0E 090.00,SINGLE FAMILY,5312 MISSIONARY WAY,NaN,BRENTWOOD,2/14/13,228975,20130221-0017646,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,158 12 0 012.00,SINGLE FAMILY,1706 OLD HICKORY BLVD,NaN,BRENTWOOD,2/28/13,566920,20130301-0020593,No,No,...,222400.0,566900.0,5180.85000,FULL BSMT,1968.0,BRICK,A,3.0,4.0,1.0
636,159 00 0 194.00,SINGLE FAMILY,1428 OLD HICKORY BLVD,NaN,BRENTWOOD,2/4/13,650000,20130212-0014288,No,No,...,561100.0,876100.0,6284.00000,SLAB,1977.0,BRICK,A,5.0,5.0,0.0
637,159 02 0 037.00,SINGLE FAMILY,1235 CARL SEYFERT MEMORIAL DR,NaN,BRENTWOOD,2/11/13,456500,20130219-0015948,No,No,...,179300.0,494300.0,3618.00000,PT BSMT,1974.0,BRICK,B,4.0,4.0,0.0
638,159 10 0B 002.00,VACANT RES LAND,5632 GRANNY WHITE PIKE,NaN,BRENTWOOD,2/11/13,245000,20130219-0016118,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,160 12 0 192.00,SINGLE FAMILY,6032 MANOR PL,NaN,BRENTWOOD,3/15/13,380500,20130320-0027543,No,No,...,282100.0,342100.0,3257.00000,CRAWL,1987.0,BRICK,B,4.0,3.0,0.0
901,160 14 0B 070.00,RESIDENTIAL CONDO,5770 BRENTWOOD TRCE,NaN,BRENTWOOD,3/11/13,137000,20130319-0027072,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,160 15 0A 010.00,RESIDENTIAL CONDO,141 HEARTHSTONE MANOR CIR,NaN,BRENTWOOD,3/21/13,227500,20130322-0028511,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54015,181 11 0B 112.00,SINGLE FAMILY,9136 CARISSA DR,NaN,BRENTWOOD,9/29/16,249900,20161003-0103840,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54016,181 11 0C 049.00,RESIDENTIAL CONDO,8315 ROSSI RD,NaN,BRENTWOOD,9/16/16,205000,20160922-0099898,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54017,181 14 0A 021.00,RESIDENTIAL CONDO,8302 OAK KNOLL DR,NaN,BRENTWOOD,9/23/16,205000,20160926-0101063,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54018,181 14 0A 043.00,RESIDENTIAL CONDO,8102 VALLEY OAK DR,NaN,BRENTWOOD,9/19/16,209000,20160921-0099352,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54019,181 14 0A 079.00,RESIDENTIAL CONDO,8269 ROSSI RD,NaN,BRENTWOOD,9/30/16,185000,20161006-0106057,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54399,159 00 0 031.00,VACANT RESIDENTIAL LAND,1404 OLD HICKORY BLVD,NaN,BRENTWOOD,9/9/16,450000,20160912-0095643,Yes,Yes,...,0.0,632200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54400,159 00 0 057.00,SINGLE FAMILY,1134 OMAN DR,NaN,BRENTWOOD,9/1/16,510000,20160907-0093836,No,No,...,157500.0,448900.0,2303.00000,CRAWL,1960.0,BRICK,B,3.0,3.0,0.0
54401,159 00 0 157.00,VACANT RESIDENTIAL LAND,5629 HILLVIEW DR,NaN,BRENTWOOD,9/13/16,285000,20160920-0098772,Yes,No,...,0.0,235000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54402,159 00 0 234.00,VACANT RESIDENTIAL LAND,1400 OLD HICKORY BLVD,NaN,BRENTWOOD,9/9/16,450000,20160912-0095643,Yes,Yes,...,0.0,421200.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
54403,159 00 0 235.00,VACANT RESIDENTIAL LAND,1408 OLD HICKORY BLVD,NaN,BRENTWOOD,9/9/16,450000,20160912-0095643,Yes,Yes,...,0.0,318000.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
54404,159 00 0 255.00,SINGLE FAMILY,5 AGINCOURT WAY,NaN,BRENTWOOD,9/15/16,1500000,20160920-0098693,No,No,...,1006500.0,1318300.0,6302.22998,CRAWL,2005.0,BRICK,X,5.0,3.0,2.0
54405,159 02 0 071.00,SINGLE FAMILY,1100 RADNOR GLEN DR,NaN,BRENTWOOD,9/8/16,1025000,20160912-0095769,No,No,...,749500.0,989500.0,6258.00000,CRAWL,2000.0,BRICK,X,5.0,3.0,1.0
54406,159 06 0B 019.00,VACANT RESIDENTIAL LAND,1716 WOODSONG DR,NaN,BRENTWOOD,9/15/16,364900,20160916-0097696,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54407,159 07 0A 002.00,VACANT RESIDENTIAL LAND,5005 HIGH VALLEY DR,NaN,BRENTWOOD,9/9/16,117500,20160913-0096078,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55405,160 10 0A 005.00,SINGLE FAMILY,104 HEATHER WAY,NaN,BRENTWOOD,10/18/16,440000,20161021-0111298,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55406,160 11 0 060.00,SINGLE FAMILY,537 HEARTHSTONE CIR,NaN,BRENTWOOD,10/28/16,435000,20161101-0115141,No,No,...,278200.0,338600.0,3360.00000,CRAWL,1986.0,BRICK,B,4.0,3.0,0.0
55407,160 15 0A 002.00,RESIDENTIAL CONDO,102 HEARTHSTONE MANOR CIR,NaN,BRENTWOOD,10/7/16,206500,20161101-0115453,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55448,171 02 0A 100.00,RESIDENTIAL CONDO,209 GLENSTONE CIR,NaN,BRENTWOOD,10/3/16,290800,20161004-0104822,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55449,171 03 0A 131.00,SINGLE FAMILY,5336 FREDERICKSBURG WAY W,NaN,BRENTWOOD,10/25/16,360000,20161031-0114735,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55450,171 03 0A 154.00,SINGLE FAMILY,1105 LANGLEY PL,NaN,BRENTWOOD,10/14/16,395000,20161017-0109331,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55451,171 03 0B 248.00,RESIDENTIAL CONDO,601 OLD HICKORY BLVD,52,BRENTWOOD,10/26/16,245000,20161027-0113706,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55453,172 01 0A 112.00,SINGLE FAMILY,86 TROTWOOD CIR,NaN,BRENTWOOD,10/14/16,357000,20161020-0110821,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55458,172 05 0B 143.00,SINGLE FAMILY,412 CARPHILLY CT,NaN,BRENTWOOD,10/26/16,341500,20161031-0114933,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55459,172 05 0B 162.00,SINGLE FAMILY,5904 WESTHEIMER DR,NaN,BRENTWOOD,10/28/16,350000,20161031-0114844,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55462,172 09 0A 056.00,SINGLE FAMILY,6537 BANBURY XING,NaN,BRENTWOOD,10/14/16,430000,20161017-0109266,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55531,181 03 0A 301.00,SINGLE FAMILY,8020 MANDAN DR,NaN,BRENTWOOD,10/21/16,285000,20161027-0113612,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55532,181 10 0D 019.00,SINGLE FAMILY,477 HIGH POINT TER,NaN,BRENTWOOD,10/5/16,439900,20161007-0106316,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55533,181 10 0E 012.00,SINGLE FAMILY,5115 ANDER DR,NaN,BRENTWOOD,10/28/16,250000,20161101-0115495,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55534,181 14 0A 107.00,RESIDENTIAL CONDO,8603 ALTESSE WAY,NaN,BRENTWOOD,10/31/16,212000,20161102-0115738,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55535,181 14 0A 217.00,RESIDENTIAL CONDO,8728 AMBONNAY DR,NaN,BRENTWOOD,10/17/16,205000,20161026-0113272,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q2c. [10pts] How many houses  were sold in 2014?

In [8]:
# YOUR CODE HERE
import datetime
df['Year'] = pd.DatetimeIndex(df['Sale Date']).year

In [ ]:
##another way you can do it
#cond = df['Sale Date'].str.endswith('14')

In [9]:
sold_fourteen = df[df['Year'] == 2014]
print("There were", sold_fourteen['Year'].count(), "houses sold in 2014.")

There were 14297 houses sold in 2014.

### Q2d. [10pts] How many houses  in the Antioch area were sold in 2015?

In [11]:
# YOUR CODE HERE
ft = df[(df['Year'] == 2015)] 
ft_ant = ft[ft['Property City'].str.upper() == 'ANTIOCH']
print("There were", ft_ant['Year'].count(), "houses sold in the Antioch area in 2015.")

There were 2029 houses sold in the Antioch area in 2015.

In [ ]:
##another way you can do it: Two steps
#First, select all records in Antioch
##cond1 = df['Property City'].str.upper() == 'ANTIOCH'
##antioch_houses = df[cond1]
#Second, select all houses sold in 2015
##cond2 = df['Sale Date'].str.endswith('15')
##len(antioch_houses[cond2])

In [17]:
##another way to do it in one line
##df[(df['Year'] == 2015) & (df['Property City'] == 'ANTIOCH')]['Year'].count()

##here the letters 'and' are boolean and the symbol '&'

2029

### Q2e. [10pts] What was the average house price in 2013?

In [18]:
# YOUR CODE HERE
tt = df[df['Year'] == 2013]
sum = tt['Sale Price'].sum()
count = tt['Year'].count()
avg = sum/count
print("The average house price in 2013 was $%.2f" % avg)

The average house price in 2013 was $245489.80

In [23]:
tt['Sale Price'].median()
##tt['Sale Price'].describe()

180000.0

In [24]:
tt['Sale Price'].mean()

245489.79739138097

### Q2f. [10pts] What was the average price of 4-bedroom houses in the Nashville area between 2013 and 2016?

In [25]:
# YOUR CODE HERE
nash = df[df['Property City'].str.upper() == 'NASHVILLE']
four_nash = nash[nash['Bedrooms'] == 4]
sum = four_nash['Sale Price'].sum()
count = four_nash['Year'].count()
avg = sum/count
print("The average price of a 4-bedroom house in the Nashville area between 2013 and 2016 was $%.2f." % avg )

The average price of a 4-bedroom house in the Nashville area between 2013 and 2016 was $436825.34.

### Q2g. [10pts] Remove the State, Image, and Parcel ID columns

In [26]:
# YOUR CODE HERE
del df['State']
del df['image']
del df['Parcel ID']
df.columns

Index(['Land Use', 'Property Address', 'Suite/ Condo   #', 'Property City',
       'Sale Date', 'Sale Price', 'Legal Reference', 'Sold As Vacant',
       'Multiple Parcels Involved in Sale', 'Owner Name', 'Address', 'City',
       'Acreage', 'Tax District', 'Neighborhood', 'Land Value',
       'Building Value', 'Total Value', 'Finished Area', 'Foundation Type',
       'Year Built', 'Exterior Wall', 'Grade', 'Bedrooms', 'Full Bath',
       'Half Bath', 'Year'],
      dtype='object')

### Q2h. [10pts] Remove all records that have at least one missing value

In [27]:
# YOUR CODE HERE
clean = df.dropna()
clean

,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,Owner Name,...,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath,Year
7822,ZERO LOT LINE,1129 CLIFTON LN,3-B,NASHVILLE,9/4/13,201000,20130909-0094904,No,No,"CRUTCHFIELD, BILL & LEAH",...,209700.0,1332.0,CRAWL,1984.0,BRICK,C,2.0,3.0,0.0,2013
24933,ZERO LOT LINE,1245 OLD HICKORY BLVD,2-A,BRENTWOOD,12/12/14,275000,20141217-0115474,No,No,"RONVEAUX, KAY B. & RICHARD C.",...,292000.0,2333.0,CRAWL,1985.0,FRAME,B,2.0,2.0,0.0,2014

### Q3i. [10pts] How many records are left in the dataframe?

In [28]:
# YOUR CODE HERE
print("There are ", clean['Property Address'].count(), " records left in the dataframe.")

There are  2  records left in the dataframe.