In [1]:
!pwd

/Users/osamples/sols/nightthree

In [3]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	acfootball_ocs.ipynb

nothing added to commit but untracked files present (use "git add" to track)

In [48]:
#importing the data
def get_page(url): 
    import requests
    response = requests.get(url)
    return response

In [49]:
##selecting the data table
def parse_page(response):
    import bs4
    soup = bs4.BeautifulSoup(response.content, 'html.parser')
    return soup

In [54]:
##selecting all data from one column and then adding to an array
 
def query_page(soup):
#getting team names 
    teams = soup.find_all('span', attrs={'class':'dn show-mobile'})

    teamslist = []
    for team in teams:
        teamslist.append(str.strip(team.text))
#getting stats
    stats = soup.find_all('span', attrs={'class': 'stat-cell'})
    statslist = []
    for stat in stats:
        statslist.append(str.strip(stat.text))  
    list1 = [statslist, teamslist]
    return list1

In [57]:
def structure_query(list1):
    statslist = list1[0] 
    teamslist = list1[1]
    #selecting only the atlantic/coastal teams
    start = 12
    end = 26
    acteams = teamslist[start: end]
    
    #selecting only the atlantic/coastal stats
    colnames = ['Conf W/L', 'Conf PF', 'Conf PA', 'Overall W/L', 'Overall PF', 'Overall PA', 'Overall Home', 'Overall Away', 'Overall STRK', 'Polls AP', 'Polls USA']
    acstats = statslist[start*len(colnames):end*len(colnames)]
    
    #Here we store each team's stats as a list into an array
    rows = []
    i = 0
    for n in range(len(acteams)):
        rows.append(acstats[i:i+len(colnames)])
        i = i+len(colnames)
    list2 = [acteams, colnames, rows]
    return  list2

In [58]:
#Now we have all of our lists. Let's make a data frame.
def make_df(list2):
    acteams = list2[0]
    colnames = list2[1]
    rows = list2[2]
    import pandas as pd
    df = pd.DataFrame({'A' : [0]}, index = colnames)

    for i in range(len(acteams)):
        df[acteams[i]] = rows[i]
    del df['A']
    return df.transpose()

In [59]:
def print_df(url):
    return make_df(structure_query(query_page(parse_page(get_page(url)))))
print_df('https://www.espn.com/college-football/standings')

,Conf W/L,Conf PF,Conf PA,Overall W/L,Overall PF,Overall PA,Overall Home,Overall Away,Overall STRK,Polls AP,Polls USA
CLEM,7-0,318,81,10-0,453,115,6-0,4-0,W10,1-0,1-0
WAKE,3-2,169,152,7-2,321,233,5-1,2-1,L1,0-0,0-0
FSU,4-4,207,210,5-5,283,290,4-2,1-3,W1,0-2,0-1
LOU,3-3,192,251,5-4,289,307,3-2,1-2,L1,1-2,1-2
BC,3-4,239,244,5-5,338,321,3-3,2-2,L1,0-1,0-2
NCST,1-4,73,185,4-5,209,258,4-1,0-4,L3,0-2,0-2
SYR,0-5,80,177,3-6,217,276,2-3,1-3,L4,0-1,0-1
UVA,5-2,210,156,7-3,310,225,5-0,2-3,W2,0-1,0-1
VT,3-2,159,173,6-3,268,245,5-1,1-2,W1,1-1,1-1
PITT,3-2,106,106,6-3,188,181,3-2,3-1,W1,1-1,1-1
MIA,4-3,193,156,6-4,293,192,4-2,2-1,W3,1-1,1-1
UNC,3-3,178,166,4-5,251,244,2-3,1-2,L1,0-1,0-1
DUKE,2-3,147,134,4-5,243,245,2-2,2-2,L3,0-2,0-2
GT,1-5,125,205,2-7,165,266,1-3,1-4,L2,0-1,0-1

In [23]:
##Initial Effort for Record

#row1 = acstats[:11]
#row2 = acstats[11:22]
#row3 = acstats[22:33]
#row4 = acstats[33:44]
#row5 = acstats[44:55]
#row6 = acstats[55:66]
#row7 = acstats[66:77]
#row8 = acstats[77:88]
#row9 = acstats[88:99]
#row10 = acstats[99:110]
#row11 = acstats[110:121]
#row12 = acstats[121: 132]
#row13 = acstats[132:143]
#row14 = acstats[143:154]

#acdf=pd.DataFrame({acteams[0]:rows[0], acteams[1]:rows[1], acteams[2]:rows[2], acteams[3]:rows[3], acteams[4]:rows[4], acteams[5]:rows[5],
                #acteams[6]:rows[6], acteams[7]:rows[7], acteams[8]:rows[8], acteams[9]:rows[9], acteams[10]:rows[10], acteams[11]:rows[11],
                 #acteams[12]:rows[12], acteams[13]:rows[13]}, index = ['Conf W/L', 'Conf PF', 'Conf PA', 'Overall W/L', 'Overall PF', 'Overall PA', 'Overall Home', 'Overall Away', 'Overall STRK', 'Polls AP', 'Polls USA'])
#acdf.transpose